/* @generated by cargo run -p xtask -- docs generate. Do not edit directly. */

import doc_index from '@soyuz-docs/docs/pages/index.md?raw';
import doc_getting_started_installation from '@soyuz-docs/docs/pages/getting-started/installation.md?raw';
import doc_getting_started_quick_start from '@soyuz-docs/docs/pages/getting-started/quick-start.md?raw';
import doc_getting_started_studio from '@soyuz-docs/docs/pages/getting-started/studio.md?raw';
import doc_concepts_sdf from '@soyuz-docs/docs/pages/concepts/sdf.md?raw';
import doc_concepts_primitives from '@soyuz-docs/docs/pages/concepts/primitives.md?raw';
import doc_concepts_operations from '@soyuz-docs/docs/pages/concepts/operations.md?raw';
import doc_concepts_transforms from '@soyuz-docs/docs/pages/concepts/transforms.md?raw';
import doc_concepts_modifiers from '@soyuz-docs/docs/pages/concepts/modifiers.md?raw';
import doc_api_overview from '@soyuz-docs/docs/pages/api/overview.md?raw';
import doc_cookbook_recipes_overview from '@soyuz-docs/docs/pages/cookbook/recipes-overview.md?raw';
import doc_cookbook_patterns from '@soyuz-docs/docs/pages/cookbook/patterns.md?raw';
import doc_cookbook_tips from '@soyuz-docs/docs/pages/cookbook/tips.md?raw';

export type DocsPage = {
	id: string;
	href: string;
	title: string;
	description: string;
	section: string;
	kind: 'markdown' | 'api';
	content?: string;
	apiCategories?: string[];
};

export const docsSite = { title: "Documentation", description: "Studio workflows, SDF concepts, API reference, and procedural modeling recipes." } as const;

export const docsPages: DocsPage[] = [
	{
		id: "index",
		href: "/docs",
		title: "Documentation",
		description: "The top-level documentation index.",
		section: "Overview",
		kind: "markdown",
		content: doc_index,
	},
	{
		id: "getting-started/installation",
		href: "/docs/getting-started",
		title: "Installation",
		description: "Get Soyuz running on your machine.",
		section: "Getting Started",
		kind: "markdown",
		content: doc_getting_started_installation,
	},
	{
		id: "getting-started/quick-start",
		href: "/docs/getting-started/quick-start",
		title: "Quick Start",
		description: "Create your first 3D model in a few minutes.",
		section: "Getting Started",
		kind: "markdown",
		content: doc_getting_started_quick_start,
	},
	{
		id: "getting-started/studio",
		href: "/docs/getting-started/studio",
		title: "Soyuz Studio",
		description: "Use the desktop workbench for scripts, preview, and export.",
		section: "Getting Started",
		kind: "markdown",
		content: doc_getting_started_studio,
	},
	{
		id: "concepts/sdf",
		href: "/docs/concepts",
		title: "Signed Distance Fields",
		description: "The mathematical foundation of Soyuz.",
		section: "Concepts",
		kind: "markdown",
		content: doc_concepts_sdf,
	},
	{
		id: "concepts/primitives",
		href: "/docs/concepts/primitives",
		title: "Primitives",
		description: "Basic shapes that form the building blocks of your models.",
		section: "Concepts",
		kind: "markdown",
		content: doc_concepts_primitives,
	},
	{
		id: "concepts/operations",
		href: "/docs/concepts/operations",
		title: "Boolean Operations",
		description: "Combine shapes with union, subtract, and intersect.",
		section: "Concepts",
		kind: "markdown",
		content: doc_concepts_operations,
	},
	{
		id: "concepts/transforms",
		href: "/docs/concepts/transforms",
		title: "Transforms",
		description: "Move, rotate, scale, and mirror shapes.",
		section: "Concepts",
		kind: "markdown",
		content: doc_concepts_transforms,
	},
	{
		id: "concepts/modifiers",
		href: "/docs/concepts/modifiers",
		title: "Modifiers",
		description: "Transform surfaces and repeat shapes.",
		section: "Concepts",
		kind: "markdown",
		content: doc_concepts_modifiers,
	},
	{
		id: "api/overview",
		href: "/docs/api",
		title: "API Reference",
		description: "Complete reference for all Soyuz functions.",
		section: "API Reference",
		kind: "markdown",
		content: doc_api_overview,
	},
	{
		id: "api/primitives",
		href: "/docs/api/primitives",
		title: "Primitives API",
		description: "Shape constructors available in Soyuz scripts.",
		section: "API Reference",
		kind: "api",
		apiCategories: ["primitives"],
	},
	{
		id: "api/operations",
		href: "/docs/api/operations",
		title: "Operations API",
		description: "Boolean operations, modifiers, and repetition methods.",
		section: "API Reference",
		kind: "api",
		apiCategories: ["operations", "modifiers"],
	},
	{
		id: "api/transforms",
		href: "/docs/api/transforms",
		title: "Transforms API",
		description: "Positioning, rotation, scale, symmetry, and math helpers.",
		section: "API Reference",
		kind: "api",
		apiCategories: ["transforms", "math"],
	},
	{
		id: "api/environment",
		href: "/docs/api/environment",
		title: "Environment API",
		description: "Lighting, material, sky, fog, effects, and presets.",
		section: "API Reference",
		kind: "api",
		apiCategories: ["environment"],
	},
	{
		id: "cookbook/recipes-overview",
		href: "/docs/cookbook",
		title: "Recipes Overview",
		description: "Practical modeling recipes and example families.",
		section: "Cookbook",
		kind: "markdown",
		content: doc_cookbook_recipes_overview,
	},
	{
		id: "cookbook/patterns",
		href: "/docs/cookbook/patterns",
		title: "Common Patterns",
		description: "Reusable techniques for everyday modeling.",
		section: "Cookbook",
		kind: "markdown",
		content: doc_cookbook_patterns,
	},
	{
		id: "cookbook/tips",
		href: "/docs/cookbook/tips",
		title: "Tips & Tricks",
		description: "Best practices for effective modeling.",
		section: "Cookbook",
		kind: "markdown",
		content: doc_cookbook_tips,
	},
];

export const docsSections = [
	{
		id: "overview",
		title: "Overview",
		description: "Start from the documentation index.",
		items: docsPages.filter((page) => page.section === "Overview"),
	},
	{
		id: "getting-started",
		title: "Getting Started",
		description: "Install Soyuz Studio and create your first procedural asset.",
		items: docsPages.filter((page) => page.section === "Getting Started"),
	},
	{
		id: "concepts",
		title: "Concepts",
		description: "Understand the fundamentals of Signed Distance Fields.",
		items: docsPages.filter((page) => page.section === "Concepts"),
	},
	{
		id: "api",
		title: "API Reference",
		description: "Complete reference for all Soyuz functions.",
		items: docsPages.filter((page) => page.section === "API Reference"),
	},
	{
		id: "cookbook",
		title: "Cookbook",
		description: "Recipes and patterns for common modeling tasks.",
		items: docsPages.filter((page) => page.section === "Cookbook"),
	},
];

export function getDocPage(href: string): DocsPage | undefined {
	return docsPages.find((page) => page.href === href || page.id === href);
}
