/* @generated by cargo run -p xtask -- theme generate. Do not edit directly. */

export const soyuzTheme = {
	meta: { id: "soyuz-graphite", name: "Soyuz Graphite" },
	colors: {
		accent: "#4da3ff",
		sdf: "#4ec9b0",
		text: "#e6edf3",
		textMuted: "#a7b0bd",
		border: "#2b3543",
	},
	status: {
		ready: { background: "#11263a", text: "#78bbff" },
		success: { background: "#10352f", text: "#4ec9b0" },
		warning: { background: "#332a00", text: "#f2cc60" },
		error: { background: "#3a1711", text: "#f48771" },
	},
	diagram: { box: "#f8f7f4", line: "#1a1a1a", highlight: "#4ec9b0", text: "#1a1a1a", shadow: "#1a1a1a" },
	renderer: {
		clearValue: { r: 0.101961, g: 0.101961, b: 0.101961, a: 1.0 },
		environment: {
			sunDirection: [0.5, 0.8, 0.3],
			sunColor: [1.0, 0.95, 0.9],
			sunIntensity: 1.2,
			ambientColor: [0.4, 0.5, 0.7],
			ambientIntensity: 0.3,
			materialColor: [0.7, 0.7, 0.7],
			materialShininess: 32.0,
			specularIntensity: 0.5,
			skyHorizon: [0.8, 0.85, 0.9],
			skyZenith: [0.4, 0.6, 0.9],
			fogColor: [0.8, 0.85, 0.9],
			fogDensity: 0.0,
			aoEnabled: 1.0,
			aoIntensity: 0.5,
			shadowsEnabled: 1.0,
			shadowSoftness: 16.0,
		},
	},
} as const;

export type SoyuzTheme = typeof soyuzTheme;
